postgres:
  container_name: postgres
  restart: always
  image: postgres:latest
  volumes:
  - ./postgres-data:/var/lib/postgresql/data
  ports:
    - 5432:5432

mysql:
  container_name: mysql
  restart: always
  image: mysql:latest
  environment:
    MYSQL_ROOT_PASSWORD: 'mysql'
    MYSQL_USER: 'mysql'
    MYSQL_PASS: 'mysql'
  command: mysqld --max_allowed_packet=4000M
  volumes:
  - ./mysql_data:/var/lib/mysql
  ports:
  - "3306:3306"
