postgres:
  container_name: imdb
  restart: always
  image: postgres:latest
  environment:
    POSTGRES_PASSWORD: example
  volumes:
  - ~/.postgres-data:/var/lib/postgresql/data
  ports:
    - 5433:5432
